(cl:in-package niryo_one_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          RPI_TEMPERATURE-VAL
          RPI_TEMPERATURE
          HARDWARE_VERSION-VAL
          HARDWARE_VERSION
          CONNECTION_UP-VAL
          CONNECTION_UP
          ERROR_MESSAGE-VAL
          ERROR_MESSAGE
          CALIBRATION_NEEDED-VAL
          CALIBRATION_NEEDED
          CALIBRATION_IN_PROGRESS-VAL
          CALIBRATION_IN_PROGRESS
          MOTOR_NAMES-VAL
          MOTOR_NAMES
          MOTOR_TYPES-VAL
          MOTOR_TYPES
          TEMPERATURES-VAL
          TEMPERATURES
          VOLTAGES-VAL
          VOLTAGES
          HARDWARE_ERRORS-VAL
          HARDWARE_ERRORS
))