; Auto-generated. Do not edit!


(cl:in-package niryo_one_msgs-msg)


;//! \htmlinclude SequenceGoal.msg.html

(cl:defclass <SequenceGoal> (roslisp-msg-protocol:ros-message)
  ((cmd_type
    :reader cmd_type
    :initarg :cmd_type
    :type cl:integer
    :initform 0)
   (sequence_id
    :reader sequence_id
    :initarg :sequence_id
    :type cl:integer
    :initform 0)
   (sequence
    :reader sequence
    :initarg :sequence
    :type niryo_one_msgs-msg:Sequence
    :initform (cl:make-instance 'niryo_one_msgs-msg:Sequence)))
)

(cl:defclass SequenceGoal (<SequenceGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SequenceGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SequenceGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name niryo_one_msgs-msg:<SequenceGoal> is deprecated: use niryo_one_msgs-msg:SequenceGoal instead.")))

(cl:ensure-generic-function 'cmd_type-val :lambda-list '(m))
(cl:defmethod cmd_type-val ((m <SequenceGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader niryo_one_msgs-msg:cmd_type-val is deprecated.  Use niryo_one_msgs-msg:cmd_type instead.")
  (cmd_type m))

(cl:ensure-generic-function 'sequence_id-val :lambda-list '(m))
(cl:defmethod sequence_id-val ((m <SequenceGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader niryo_one_msgs-msg:sequence_id-val is deprecated.  Use niryo_one_msgs-msg:sequence_id instead.")
  (sequence_id m))

(cl:ensure-generic-function 'sequence-val :lambda-list '(m))
(cl:defmethod sequence-val ((m <SequenceGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader niryo_one_msgs-msg:sequence-val is deprecated.  Use niryo_one_msgs-msg:sequence instead.")
  (sequence m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SequenceGoal>) ostream)
  "Serializes a message object of type '<SequenceGoal>"
  (cl:let* ((signed (cl:slot-value msg 'cmd_type)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let* ((signed (cl:slot-value msg 'sequence_id)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'sequence) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SequenceGoal>) istream)
  "Deserializes a message object of type '<SequenceGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'cmd_type) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'sequence_id) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'sequence) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SequenceGoal>)))
  "Returns string type for a message object of type '<SequenceGoal>"
  "niryo_one_msgs/SequenceGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SequenceGoal)))
  "Returns string type for a message object of type 'SequenceGoal"
  "niryo_one_msgs/SequenceGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SequenceGoal>)))
  "Returns md5sum for a message object of type '<SequenceGoal>"
  "da644ff8e5065e5598b50f9f1180dd4c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SequenceGoal)))
  "Returns md5sum for a message object of type 'SequenceGoal"
  "da644ff8e5065e5598b50f9f1180dd4c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SequenceGoal>)))
  "Returns full string definition for message of type '<SequenceGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%int32 cmd_type~%int32 sequence_id~%niryo_one_msgs/Sequence sequence~%~%================================================================================~%MSG: niryo_one_msgs/Sequence~%int32 id~%string name~%string description~%~%int32 created~%int32 updated~%~%string blockly_xml~%string python_code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SequenceGoal)))
  "Returns full string definition for message of type 'SequenceGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%int32 cmd_type~%int32 sequence_id~%niryo_one_msgs/Sequence sequence~%~%================================================================================~%MSG: niryo_one_msgs/Sequence~%int32 id~%string name~%string description~%~%int32 created~%int32 updated~%~%string blockly_xml~%string python_code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SequenceGoal>))
  (cl:+ 0
     4
     4
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'sequence))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SequenceGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SequenceGoal
    (cl:cons ':cmd_type (cmd_type msg))
    (cl:cons ':sequence_id (sequence_id msg))
    (cl:cons ':sequence (sequence msg))
))
