; Auto-generated. Do not edit!


(cl:in-package niryo_one_msgs-msg)


;//! \htmlinclude ToolGoal.msg.html

(cl:defclass <ToolGoal> (roslisp-msg-protocol:ros-message)
  ((cmd
    :reader cmd
    :initarg :cmd
    :type niryo_one_msgs-msg:ToolCommand
    :initform (cl:make-instance 'niryo_one_msgs-msg:ToolCommand)))
)

(cl:defclass ToolGoal (<ToolGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ToolGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ToolGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name niryo_one_msgs-msg:<ToolGoal> is deprecated: use niryo_one_msgs-msg:ToolGoal instead.")))

(cl:ensure-generic-function 'cmd-val :lambda-list '(m))
(cl:defmethod cmd-val ((m <ToolGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader niryo_one_msgs-msg:cmd-val is deprecated.  Use niryo_one_msgs-msg:cmd instead.")
  (cmd m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ToolGoal>) ostream)
  "Serializes a message object of type '<ToolGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'cmd) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ToolGoal>) istream)
  "Deserializes a message object of type '<ToolGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'cmd) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ToolGoal>)))
  "Returns string type for a message object of type '<ToolGoal>"
  "niryo_one_msgs/ToolGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ToolGoal)))
  "Returns string type for a message object of type 'ToolGoal"
  "niryo_one_msgs/ToolGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ToolGoal>)))
  "Returns md5sum for a message object of type '<ToolGoal>"
  "c773218b26dbc38b2561cc0aa2e21da9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ToolGoal)))
  "Returns md5sum for a message object of type 'ToolGoal"
  "c773218b26dbc38b2561cc0aa2e21da9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ToolGoal>)))
  "Returns full string definition for message of type '<ToolGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%niryo_one_msgs/ToolCommand cmd~%~%================================================================================~%MSG: niryo_one_msgs/ToolCommand~%~%uint8 tool_id~%uint8 cmd_type~%~%# if gripper close~%uint16 gripper_close_speed~%~%# if gripper open~%uint16 gripper_open_speed~%~%# if vacuum pump or electromagnet grove~%bool activate~%~%# if tool is set by digital outputs (electromagnet)~%uint8 gpio~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ToolGoal)))
  "Returns full string definition for message of type 'ToolGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%niryo_one_msgs/ToolCommand cmd~%~%================================================================================~%MSG: niryo_one_msgs/ToolCommand~%~%uint8 tool_id~%uint8 cmd_type~%~%# if gripper close~%uint16 gripper_close_speed~%~%# if gripper open~%uint16 gripper_open_speed~%~%# if vacuum pump or electromagnet grove~%bool activate~%~%# if tool is set by digital outputs (electromagnet)~%uint8 gpio~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ToolGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'cmd))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ToolGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ToolGoal
    (cl:cons ':cmd (cmd msg))
))
