// Auto-generated. Do not edit!

// (in-package niryo_one_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class JoystickJointsFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.is_in_joints_limit = null;
    }
    else {
      if (initObj.hasOwnProperty('is_in_joints_limit')) {
        this.is_in_joints_limit = initObj.is_in_joints_limit
      }
      else {
        this.is_in_joints_limit = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type JoystickJointsFeedback
    // Serialize message field [is_in_joints_limit]
    bufferOffset = _serializer.bool(obj.is_in_joints_limit, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type JoystickJointsFeedback
    let len;
    let data = new JoystickJointsFeedback(null);
    // Deserialize message field [is_in_joints_limit]
    data.is_in_joints_limit = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'niryo_one_msgs/JoystickJointsFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'ef8713044a4f11ece629bb8e0a3e2058';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # feedback 
    bool is_in_joints_limit
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new JoystickJointsFeedback(null);
    if (msg.is_in_joints_limit !== undefined) {
      resolved.is_in_joints_limit = msg.is_in_joints_limit;
    }
    else {
      resolved.is_in_joints_limit = false
    }

    return resolved;
    }
};

module.exports = JoystickJointsFeedback;
