// Auto-generated. Do not edit!

// (in-package niryo_one_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let ToolCommand = require('./ToolCommand.js');

//-----------------------------------------------------------

class ToolGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.cmd = null;
    }
    else {
      if (initObj.hasOwnProperty('cmd')) {
        this.cmd = initObj.cmd
      }
      else {
        this.cmd = new ToolCommand();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ToolGoal
    // Serialize message field [cmd]
    bufferOffset = ToolCommand.serialize(obj.cmd, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ToolGoal
    let len;
    let data = new ToolGoal(null);
    // Deserialize message field [cmd]
    data.cmd = ToolCommand.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'niryo_one_msgs/ToolGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c773218b26dbc38b2561cc0aa2e21da9';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal
    niryo_one_msgs/ToolCommand cmd
    
    ================================================================================
    MSG: niryo_one_msgs/ToolCommand
    
    uint8 tool_id
    uint8 cmd_type
    
    # if gripper close
    uint16 gripper_close_speed
    
    # if gripper open
    uint16 gripper_open_speed
    
    # if vacuum pump or electromagnet grove
    bool activate
    
    # if tool is set by digital outputs (electromagnet)
    uint8 gpio
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ToolGoal(null);
    if (msg.cmd !== undefined) {
      resolved.cmd = ToolCommand.Resolve(msg.cmd)
    }
    else {
      resolved.cmd = new ToolCommand()
    }

    return resolved;
    }
};

module.exports = ToolGoal;
