// Generated by gencpp from file niryo_one_msgs/ChangeHardwareVersion.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_CHANGEHARDWAREVERSION_H
#define NIRYO_ONE_MSGS_MESSAGE_CHANGEHARDWAREVERSION_H

#include <ros/service_traits.h>


#include <niryo_one_msgs/ChangeHardwareVersionRequest.h>
#include <niryo_one_msgs/ChangeHardwareVersionResponse.h>


namespace niryo_one_msgs
{

struct ChangeHardwareVersion
{

typedef ChangeHardwareVersionRequest Request;
typedef ChangeHardwareVersionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeHardwareVersion
} // namespace niryo_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_one_msgs::ChangeHardwareVersion > {
  static const char* value()
  {
    return "a236aed5507cea948ac43373e4211c23";
  }

  static const char* value(const ::niryo_one_msgs::ChangeHardwareVersion&) { return value(); }
};

template<>
struct DataType< ::niryo_one_msgs::ChangeHardwareVersion > {
  static const char* value()
  {
    return "niryo_one_msgs/ChangeHardwareVersion";
  }

  static const char* value(const ::niryo_one_msgs::ChangeHardwareVersion&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_one_msgs::ChangeHardwareVersionRequest> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::ChangeHardwareVersion > 
template<>
struct MD5Sum< ::niryo_one_msgs::ChangeHardwareVersionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::ChangeHardwareVersion >::value();
  }
  static const char* value(const ::niryo_one_msgs::ChangeHardwareVersionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::ChangeHardwareVersionRequest> should match 
// service_traits::DataType< ::niryo_one_msgs::ChangeHardwareVersion > 
template<>
struct DataType< ::niryo_one_msgs::ChangeHardwareVersionRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::ChangeHardwareVersion >::value();
  }
  static const char* value(const ::niryo_one_msgs::ChangeHardwareVersionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_one_msgs::ChangeHardwareVersionResponse> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::ChangeHardwareVersion > 
template<>
struct MD5Sum< ::niryo_one_msgs::ChangeHardwareVersionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::ChangeHardwareVersion >::value();
  }
  static const char* value(const ::niryo_one_msgs::ChangeHardwareVersionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::ChangeHardwareVersionResponse> should match 
// service_traits::DataType< ::niryo_one_msgs::ChangeHardwareVersion > 
template<>
struct DataType< ::niryo_one_msgs::ChangeHardwareVersionResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::ChangeHardwareVersion >::value();
  }
  static const char* value(const ::niryo_one_msgs::ChangeHardwareVersionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_CHANGEHARDWAREVERSION_H
