// Generated by gencpp from file niryo_one_msgs/CloseGripper.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_CLOSEGRIPPER_H
#define NIRYO_ONE_MSGS_MESSAGE_CLOSEGRIPPER_H

#include <ros/service_traits.h>


#include <niryo_one_msgs/CloseGripperRequest.h>
#include <niryo_one_msgs/CloseGripperResponse.h>


namespace niryo_one_msgs
{

struct CloseGripper
{

typedef CloseGripperRequest Request;
typedef CloseGripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CloseGripper
} // namespace niryo_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_one_msgs::CloseGripper > {
  static const char* value()
  {
    return "04901e0d312f8ee9c675fc0042c3a8e4";
  }

  static const char* value(const ::niryo_one_msgs::CloseGripper&) { return value(); }
};

template<>
struct DataType< ::niryo_one_msgs::CloseGripper > {
  static const char* value()
  {
    return "niryo_one_msgs/CloseGripper";
  }

  static const char* value(const ::niryo_one_msgs::CloseGripper&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_one_msgs::CloseGripperRequest> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::CloseGripper > 
template<>
struct MD5Sum< ::niryo_one_msgs::CloseGripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::CloseGripper >::value();
  }
  static const char* value(const ::niryo_one_msgs::CloseGripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::CloseGripperRequest> should match 
// service_traits::DataType< ::niryo_one_msgs::CloseGripper > 
template<>
struct DataType< ::niryo_one_msgs::CloseGripperRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::CloseGripper >::value();
  }
  static const char* value(const ::niryo_one_msgs::CloseGripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_one_msgs::CloseGripperResponse> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::CloseGripper > 
template<>
struct MD5Sum< ::niryo_one_msgs::CloseGripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::CloseGripper >::value();
  }
  static const char* value(const ::niryo_one_msgs::CloseGripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::CloseGripperResponse> should match 
// service_traits::DataType< ::niryo_one_msgs::CloseGripper > 
template<>
struct DataType< ::niryo_one_msgs::CloseGripperResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::CloseGripper >::value();
  }
  static const char* value(const ::niryo_one_msgs::CloseGripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_CLOSEGRIPPER_H
