// Generated by gencpp from file niryo_one_msgs/GetSequenceList.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_GETSEQUENCELIST_H
#define NIRYO_ONE_MSGS_MESSAGE_GETSEQUENCELIST_H

#include <ros/service_traits.h>


#include <niryo_one_msgs/GetSequenceListRequest.h>
#include <niryo_one_msgs/GetSequenceListResponse.h>


namespace niryo_one_msgs
{

struct GetSequenceList
{

typedef GetSequenceListRequest Request;
typedef GetSequenceListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSequenceList
} // namespace niryo_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_one_msgs::GetSequenceList > {
  static const char* value()
  {
    return "fc93b5ac839706215135d7128129cf9a";
  }

  static const char* value(const ::niryo_one_msgs::GetSequenceList&) { return value(); }
};

template<>
struct DataType< ::niryo_one_msgs::GetSequenceList > {
  static const char* value()
  {
    return "niryo_one_msgs/GetSequenceList";
  }

  static const char* value(const ::niryo_one_msgs::GetSequenceList&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_one_msgs::GetSequenceListRequest> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::GetSequenceList > 
template<>
struct MD5Sum< ::niryo_one_msgs::GetSequenceListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::GetSequenceList >::value();
  }
  static const char* value(const ::niryo_one_msgs::GetSequenceListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::GetSequenceListRequest> should match 
// service_traits::DataType< ::niryo_one_msgs::GetSequenceList > 
template<>
struct DataType< ::niryo_one_msgs::GetSequenceListRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::GetSequenceList >::value();
  }
  static const char* value(const ::niryo_one_msgs::GetSequenceListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_one_msgs::GetSequenceListResponse> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::GetSequenceList > 
template<>
struct MD5Sum< ::niryo_one_msgs::GetSequenceListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::GetSequenceList >::value();
  }
  static const char* value(const ::niryo_one_msgs::GetSequenceListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::GetSequenceListResponse> should match 
// service_traits::DataType< ::niryo_one_msgs::GetSequenceList > 
template<>
struct DataType< ::niryo_one_msgs::GetSequenceListResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::GetSequenceList >::value();
  }
  static const char* value(const ::niryo_one_msgs::GetSequenceListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_GETSEQUENCELIST_H
