// Generated by gencpp from file niryo_one_msgs/GetWorkspaceList.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_GETWORKSPACELIST_H
#define NIRYO_ONE_MSGS_MESSAGE_GETWORKSPACELIST_H

#include <ros/service_traits.h>


#include <niryo_one_msgs/GetWorkspaceListRequest.h>
#include <niryo_one_msgs/GetWorkspaceListResponse.h>


namespace niryo_one_msgs
{

struct GetWorkspaceList
{

typedef GetWorkspaceListRequest Request;
typedef GetWorkspaceListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetWorkspaceList
} // namespace niryo_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_one_msgs::GetWorkspaceList > {
  static const char* value()
  {
    return "8b36c598e23fd962676550874c6879f7";
  }

  static const char* value(const ::niryo_one_msgs::GetWorkspaceList&) { return value(); }
};

template<>
struct DataType< ::niryo_one_msgs::GetWorkspaceList > {
  static const char* value()
  {
    return "niryo_one_msgs/GetWorkspaceList";
  }

  static const char* value(const ::niryo_one_msgs::GetWorkspaceList&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_one_msgs::GetWorkspaceListRequest> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::GetWorkspaceList > 
template<>
struct MD5Sum< ::niryo_one_msgs::GetWorkspaceListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::GetWorkspaceList >::value();
  }
  static const char* value(const ::niryo_one_msgs::GetWorkspaceListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::GetWorkspaceListRequest> should match 
// service_traits::DataType< ::niryo_one_msgs::GetWorkspaceList > 
template<>
struct DataType< ::niryo_one_msgs::GetWorkspaceListRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::GetWorkspaceList >::value();
  }
  static const char* value(const ::niryo_one_msgs::GetWorkspaceListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_one_msgs::GetWorkspaceListResponse> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::GetWorkspaceList > 
template<>
struct MD5Sum< ::niryo_one_msgs::GetWorkspaceListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::GetWorkspaceList >::value();
  }
  static const char* value(const ::niryo_one_msgs::GetWorkspaceListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::GetWorkspaceListResponse> should match 
// service_traits::DataType< ::niryo_one_msgs::GetWorkspaceList > 
template<>
struct DataType< ::niryo_one_msgs::GetWorkspaceListResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::GetWorkspaceList >::value();
  }
  static const char* value(const ::niryo_one_msgs::GetWorkspaceListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_GETWORKSPACELIST_H
