// Generated by gencpp from file niryo_one_msgs/ManageTrajectory.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_MANAGETRAJECTORY_H
#define NIRYO_ONE_MSGS_MESSAGE_MANAGETRAJECTORY_H

#include <ros/service_traits.h>


#include <niryo_one_msgs/ManageTrajectoryRequest.h>
#include <niryo_one_msgs/ManageTrajectoryResponse.h>


namespace niryo_one_msgs
{

struct ManageTrajectory
{

typedef ManageTrajectoryRequest Request;
typedef ManageTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ManageTrajectory
} // namespace niryo_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_one_msgs::ManageTrajectory > {
  static const char* value()
  {
    return "4b816dfb5d41c32402f249891f1295ce";
  }

  static const char* value(const ::niryo_one_msgs::ManageTrajectory&) { return value(); }
};

template<>
struct DataType< ::niryo_one_msgs::ManageTrajectory > {
  static const char* value()
  {
    return "niryo_one_msgs/ManageTrajectory";
  }

  static const char* value(const ::niryo_one_msgs::ManageTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_one_msgs::ManageTrajectoryRequest> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::ManageTrajectory > 
template<>
struct MD5Sum< ::niryo_one_msgs::ManageTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::ManageTrajectory >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManageTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::ManageTrajectoryRequest> should match 
// service_traits::DataType< ::niryo_one_msgs::ManageTrajectory > 
template<>
struct DataType< ::niryo_one_msgs::ManageTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::ManageTrajectory >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManageTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_one_msgs::ManageTrajectoryResponse> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::ManageTrajectory > 
template<>
struct MD5Sum< ::niryo_one_msgs::ManageTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::ManageTrajectory >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManageTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::ManageTrajectoryResponse> should match 
// service_traits::DataType< ::niryo_one_msgs::ManageTrajectory > 
template<>
struct DataType< ::niryo_one_msgs::ManageTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::ManageTrajectory >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManageTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_MANAGETRAJECTORY_H
