// Generated by gencpp from file niryo_one_msgs/ManagePosition.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_MANAGEPOSITION_H
#define NIRYO_ONE_MSGS_MESSAGE_MANAGEPOSITION_H

#include <ros/service_traits.h>


#include <niryo_one_msgs/ManagePositionRequest.h>
#include <niryo_one_msgs/ManagePositionResponse.h>


namespace niryo_one_msgs
{

struct ManagePosition
{

typedef ManagePositionRequest Request;
typedef ManagePositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ManagePosition
} // namespace niryo_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_one_msgs::ManagePosition > {
  static const char* value()
  {
    return "adf4e061b0eee7a4afcbede59727e52a";
  }

  static const char* value(const ::niryo_one_msgs::ManagePosition&) { return value(); }
};

template<>
struct DataType< ::niryo_one_msgs::ManagePosition > {
  static const char* value()
  {
    return "niryo_one_msgs/ManagePosition";
  }

  static const char* value(const ::niryo_one_msgs::ManagePosition&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_one_msgs::ManagePositionRequest> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::ManagePosition > 
template<>
struct MD5Sum< ::niryo_one_msgs::ManagePositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::ManagePosition >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManagePositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::ManagePositionRequest> should match 
// service_traits::DataType< ::niryo_one_msgs::ManagePosition > 
template<>
struct DataType< ::niryo_one_msgs::ManagePositionRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::ManagePosition >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManagePositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_one_msgs::ManagePositionResponse> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::ManagePosition > 
template<>
struct MD5Sum< ::niryo_one_msgs::ManagePositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::ManagePosition >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManagePositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::ManagePositionResponse> should match 
// service_traits::DataType< ::niryo_one_msgs::ManagePosition > 
template<>
struct DataType< ::niryo_one_msgs::ManagePositionResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::ManagePosition >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManagePositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_MANAGEPOSITION_H
