// Generated by gencpp from file niryo_one_msgs/ManageProcess.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_MANAGEPROCESS_H
#define NIRYO_ONE_MSGS_MESSAGE_MANAGEPROCESS_H

#include <ros/service_traits.h>


#include <niryo_one_msgs/ManageProcessRequest.h>
#include <niryo_one_msgs/ManageProcessResponse.h>


namespace niryo_one_msgs
{

struct ManageProcess
{

typedef ManageProcessRequest Request;
typedef ManageProcessResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ManageProcess
} // namespace niryo_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_one_msgs::ManageProcess > {
  static const char* value()
  {
    return "ed541b1426d7fc8f78be14b5e4b306cf";
  }

  static const char* value(const ::niryo_one_msgs::ManageProcess&) { return value(); }
};

template<>
struct DataType< ::niryo_one_msgs::ManageProcess > {
  static const char* value()
  {
    return "niryo_one_msgs/ManageProcess";
  }

  static const char* value(const ::niryo_one_msgs::ManageProcess&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_one_msgs::ManageProcessRequest> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::ManageProcess > 
template<>
struct MD5Sum< ::niryo_one_msgs::ManageProcessRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::ManageProcess >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManageProcessRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::ManageProcessRequest> should match 
// service_traits::DataType< ::niryo_one_msgs::ManageProcess > 
template<>
struct DataType< ::niryo_one_msgs::ManageProcessRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::ManageProcess >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManageProcessRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_one_msgs::ManageProcessResponse> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::ManageProcess > 
template<>
struct MD5Sum< ::niryo_one_msgs::ManageProcessResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::ManageProcess >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManageProcessResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::ManageProcessResponse> should match 
// service_traits::DataType< ::niryo_one_msgs::ManageProcess > 
template<>
struct DataType< ::niryo_one_msgs::ManageProcessResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::ManageProcess >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManageProcessResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_MANAGEPROCESS_H
