// Generated by gencpp from file niryo_one_msgs/ManageSequence.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_MANAGESEQUENCE_H
#define NIRYO_ONE_MSGS_MESSAGE_MANAGESEQUENCE_H

#include <ros/service_traits.h>


#include <niryo_one_msgs/ManageSequenceRequest.h>
#include <niryo_one_msgs/ManageSequenceResponse.h>


namespace niryo_one_msgs
{

struct ManageSequence
{

typedef ManageSequenceRequest Request;
typedef ManageSequenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ManageSequence
} // namespace niryo_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_one_msgs::ManageSequence > {
  static const char* value()
  {
    return "10143a290fd01d09f121d3105d3730fd";
  }

  static const char* value(const ::niryo_one_msgs::ManageSequence&) { return value(); }
};

template<>
struct DataType< ::niryo_one_msgs::ManageSequence > {
  static const char* value()
  {
    return "niryo_one_msgs/ManageSequence";
  }

  static const char* value(const ::niryo_one_msgs::ManageSequence&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_one_msgs::ManageSequenceRequest> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::ManageSequence > 
template<>
struct MD5Sum< ::niryo_one_msgs::ManageSequenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::ManageSequence >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManageSequenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::ManageSequenceRequest> should match 
// service_traits::DataType< ::niryo_one_msgs::ManageSequence > 
template<>
struct DataType< ::niryo_one_msgs::ManageSequenceRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::ManageSequence >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManageSequenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_one_msgs::ManageSequenceResponse> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::ManageSequence > 
template<>
struct MD5Sum< ::niryo_one_msgs::ManageSequenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::ManageSequence >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManageSequenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::ManageSequenceResponse> should match 
// service_traits::DataType< ::niryo_one_msgs::ManageSequence > 
template<>
struct DataType< ::niryo_one_msgs::ManageSequenceResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::ManageSequence >::value();
  }
  static const char* value(const ::niryo_one_msgs::ManageSequenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_MANAGESEQUENCE_H
