// Generated by gencpp from file niryo_one_msgs/PullAirVacuumPump.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_PULLAIRVACUUMPUMP_H
#define NIRYO_ONE_MSGS_MESSAGE_PULLAIRVACUUMPUMP_H

#include <ros/service_traits.h>


#include <niryo_one_msgs/PullAirVacuumPumpRequest.h>
#include <niryo_one_msgs/PullAirVacuumPumpResponse.h>


namespace niryo_one_msgs
{

struct PullAirVacuumPump
{

typedef PullAirVacuumPumpRequest Request;
typedef PullAirVacuumPumpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PullAirVacuumPump
} // namespace niryo_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_one_msgs::PullAirVacuumPump > {
  static const char* value()
  {
    return "fdd48b46d71dd8ff507dc76750227fa6";
  }

  static const char* value(const ::niryo_one_msgs::PullAirVacuumPump&) { return value(); }
};

template<>
struct DataType< ::niryo_one_msgs::PullAirVacuumPump > {
  static const char* value()
  {
    return "niryo_one_msgs/PullAirVacuumPump";
  }

  static const char* value(const ::niryo_one_msgs::PullAirVacuumPump&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_one_msgs::PullAirVacuumPumpRequest> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::PullAirVacuumPump > 
template<>
struct MD5Sum< ::niryo_one_msgs::PullAirVacuumPumpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::PullAirVacuumPump >::value();
  }
  static const char* value(const ::niryo_one_msgs::PullAirVacuumPumpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::PullAirVacuumPumpRequest> should match 
// service_traits::DataType< ::niryo_one_msgs::PullAirVacuumPump > 
template<>
struct DataType< ::niryo_one_msgs::PullAirVacuumPumpRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::PullAirVacuumPump >::value();
  }
  static const char* value(const ::niryo_one_msgs::PullAirVacuumPumpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_one_msgs::PullAirVacuumPumpResponse> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::PullAirVacuumPump > 
template<>
struct MD5Sum< ::niryo_one_msgs::PullAirVacuumPumpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::PullAirVacuumPump >::value();
  }
  static const char* value(const ::niryo_one_msgs::PullAirVacuumPumpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::PullAirVacuumPumpResponse> should match 
// service_traits::DataType< ::niryo_one_msgs::PullAirVacuumPump > 
template<>
struct DataType< ::niryo_one_msgs::PullAirVacuumPumpResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::PullAirVacuumPump >::value();
  }
  static const char* value(const ::niryo_one_msgs::PullAirVacuumPumpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_PULLAIRVACUUMPUMP_H
