// Generated by gencpp from file niryo_one_msgs/SendCustomDxlValue.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_SENDCUSTOMDXLVALUE_H
#define NIRYO_ONE_MSGS_MESSAGE_SENDCUSTOMDXLVALUE_H

#include <ros/service_traits.h>


#include <niryo_one_msgs/SendCustomDxlValueRequest.h>
#include <niryo_one_msgs/SendCustomDxlValueResponse.h>


namespace niryo_one_msgs
{

struct SendCustomDxlValue
{

typedef SendCustomDxlValueRequest Request;
typedef SendCustomDxlValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendCustomDxlValue
} // namespace niryo_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_one_msgs::SendCustomDxlValue > {
  static const char* value()
  {
    return "60887d5c990ef4cc959cd4f3646b638d";
  }

  static const char* value(const ::niryo_one_msgs::SendCustomDxlValue&) { return value(); }
};

template<>
struct DataType< ::niryo_one_msgs::SendCustomDxlValue > {
  static const char* value()
  {
    return "niryo_one_msgs/SendCustomDxlValue";
  }

  static const char* value(const ::niryo_one_msgs::SendCustomDxlValue&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_one_msgs::SendCustomDxlValueRequest> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::SendCustomDxlValue > 
template<>
struct MD5Sum< ::niryo_one_msgs::SendCustomDxlValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::SendCustomDxlValue >::value();
  }
  static const char* value(const ::niryo_one_msgs::SendCustomDxlValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::SendCustomDxlValueRequest> should match 
// service_traits::DataType< ::niryo_one_msgs::SendCustomDxlValue > 
template<>
struct DataType< ::niryo_one_msgs::SendCustomDxlValueRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::SendCustomDxlValue >::value();
  }
  static const char* value(const ::niryo_one_msgs::SendCustomDxlValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_one_msgs::SendCustomDxlValueResponse> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::SendCustomDxlValue > 
template<>
struct MD5Sum< ::niryo_one_msgs::SendCustomDxlValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::SendCustomDxlValue >::value();
  }
  static const char* value(const ::niryo_one_msgs::SendCustomDxlValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::SendCustomDxlValueResponse> should match 
// service_traits::DataType< ::niryo_one_msgs::SendCustomDxlValue > 
template<>
struct DataType< ::niryo_one_msgs::SendCustomDxlValueResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::SendCustomDxlValue >::value();
  }
  static const char* value(const ::niryo_one_msgs::SendCustomDxlValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_SENDCUSTOMDXLVALUE_H
