// Generated by gencpp from file niryo_one_msgs/SetInt.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_SETINT_H
#define NIRYO_ONE_MSGS_MESSAGE_SETINT_H

#include <ros/service_traits.h>


#include <niryo_one_msgs/SetIntRequest.h>
#include <niryo_one_msgs/SetIntResponse.h>


namespace niryo_one_msgs
{

struct SetInt
{

typedef SetIntRequest Request;
typedef SetIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt
} // namespace niryo_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_one_msgs::SetInt > {
  static const char* value()
  {
    return "f68558c744d504db5de688a7cf32394e";
  }

  static const char* value(const ::niryo_one_msgs::SetInt&) { return value(); }
};

template<>
struct DataType< ::niryo_one_msgs::SetInt > {
  static const char* value()
  {
    return "niryo_one_msgs/SetInt";
  }

  static const char* value(const ::niryo_one_msgs::SetInt&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_one_msgs::SetIntRequest> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::SetInt > 
template<>
struct MD5Sum< ::niryo_one_msgs::SetIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::SetInt >::value();
  }
  static const char* value(const ::niryo_one_msgs::SetIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::SetIntRequest> should match 
// service_traits::DataType< ::niryo_one_msgs::SetInt > 
template<>
struct DataType< ::niryo_one_msgs::SetIntRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::SetInt >::value();
  }
  static const char* value(const ::niryo_one_msgs::SetIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_one_msgs::SetIntResponse> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::SetInt > 
template<>
struct MD5Sum< ::niryo_one_msgs::SetIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::SetInt >::value();
  }
  static const char* value(const ::niryo_one_msgs::SetIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::SetIntResponse> should match 
// service_traits::DataType< ::niryo_one_msgs::SetInt > 
template<>
struct DataType< ::niryo_one_msgs::SetIntResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::SetInt >::value();
  }
  static const char* value(const ::niryo_one_msgs::SetIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_SETINT_H
