// Generated by gencpp from file niryo_one_msgs/SetString.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_SETSTRING_H
#define NIRYO_ONE_MSGS_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <niryo_one_msgs/SetStringRequest.h>
#include <niryo_one_msgs/SetStringResponse.h>


namespace niryo_one_msgs
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace niryo_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_one_msgs::SetString > {
  static const char* value()
  {
    return "f84b476c9d85e5a277125fce9822f626";
  }

  static const char* value(const ::niryo_one_msgs::SetString&) { return value(); }
};

template<>
struct DataType< ::niryo_one_msgs::SetString > {
  static const char* value()
  {
    return "niryo_one_msgs/SetString";
  }

  static const char* value(const ::niryo_one_msgs::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_one_msgs::SetStringRequest> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::SetString > 
template<>
struct MD5Sum< ::niryo_one_msgs::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::SetString >::value();
  }
  static const char* value(const ::niryo_one_msgs::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::SetStringRequest> should match 
// service_traits::DataType< ::niryo_one_msgs::SetString > 
template<>
struct DataType< ::niryo_one_msgs::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::SetString >::value();
  }
  static const char* value(const ::niryo_one_msgs::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_one_msgs::SetStringResponse> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::SetString > 
template<>
struct MD5Sum< ::niryo_one_msgs::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::SetString >::value();
  }
  static const char* value(const ::niryo_one_msgs::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::SetStringResponse> should match 
// service_traits::DataType< ::niryo_one_msgs::SetString > 
template<>
struct DataType< ::niryo_one_msgs::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::SetString >::value();
  }
  static const char* value(const ::niryo_one_msgs::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_SETSTRING_H
