// Generated by gencpp from file niryo_one_msgs/TakePicture.msg
// DO NOT EDIT!


#ifndef NIRYO_ONE_MSGS_MESSAGE_TAKEPICTURE_H
#define NIRYO_ONE_MSGS_MESSAGE_TAKEPICTURE_H

#include <ros/service_traits.h>


#include <niryo_one_msgs/TakePictureRequest.h>
#include <niryo_one_msgs/TakePictureResponse.h>


namespace niryo_one_msgs
{

struct TakePicture
{

typedef TakePictureRequest Request;
typedef TakePictureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TakePicture
} // namespace niryo_one_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_one_msgs::TakePicture > {
  static const char* value()
  {
    return "24518277da746ec8ade3d50c001c2adf";
  }

  static const char* value(const ::niryo_one_msgs::TakePicture&) { return value(); }
};

template<>
struct DataType< ::niryo_one_msgs::TakePicture > {
  static const char* value()
  {
    return "niryo_one_msgs/TakePicture";
  }

  static const char* value(const ::niryo_one_msgs::TakePicture&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_one_msgs::TakePictureRequest> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::TakePicture > 
template<>
struct MD5Sum< ::niryo_one_msgs::TakePictureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::TakePicture >::value();
  }
  static const char* value(const ::niryo_one_msgs::TakePictureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::TakePictureRequest> should match 
// service_traits::DataType< ::niryo_one_msgs::TakePicture > 
template<>
struct DataType< ::niryo_one_msgs::TakePictureRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::TakePicture >::value();
  }
  static const char* value(const ::niryo_one_msgs::TakePictureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_one_msgs::TakePictureResponse> should match 
// service_traits::MD5Sum< ::niryo_one_msgs::TakePicture > 
template<>
struct MD5Sum< ::niryo_one_msgs::TakePictureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_one_msgs::TakePicture >::value();
  }
  static const char* value(const ::niryo_one_msgs::TakePictureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_one_msgs::TakePictureResponse> should match 
// service_traits::DataType< ::niryo_one_msgs::TakePicture > 
template<>
struct DataType< ::niryo_one_msgs::TakePictureResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_one_msgs::TakePicture >::value();
  }
  static const char* value(const ::niryo_one_msgs::TakePictureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ONE_MSGS_MESSAGE_TAKEPICTURE_H
